apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  
#Se especifican las características de la implementación.
spec:
  replicas: 2 #Indica el numero de replicas

#Se define el selector de la implementación.
  selector:
    matchLabels:
      app: drupal

#Se define la plantilla de la implementación.
  template:
    metadata:
      labels:
        app: drupal

#Características de la plantilla.
    spec:
      containers:
        - name: drupal
          image: drupal:latest #La imagen del contenedor.
          ports:
            - containerPort: 80 #El puerto del contenedor.

#Se definen los montajes de volumen del contenedor.
          volumeMounts:
          - name: drupalpersistentstorage 
            mountPath: /drupal 

#Se definen los volúmenes de la plantilla.
      volumes: 
        - name: drupalpersistentstorage 
          persistentVolumeClaim: #La reclamación del volumen persistente.
            claimName: drupalpvcclaim 
            
---

apiVersion: v1
kind: Service
metadata:
  name: drupal

#Se especifican las características del servicio.
spec:
  type: NodePort #El tipo de servicio. NodePort permite acceder al servicio desde fuera del clúster.
  
#Se definen los puertos del servicio.  
  ports:
    - name: http
      port: 80 #El puerto del servicio
      nodePort: 30080 #El puerto del nodo al que se mapeará el puerto del servicio.
  selector:
    app: drupal

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: drupalpvcclaim 

#Se especifican las características de la reclamación del volumen persistente.
spec:
  accessModes:
    - ReadWriteOnce #El modo de acceso. ReadWriteOnce permite que el volumen sea leído y escrito por un único nodo.

#Se definen los recursos de la reclamación del volumen persistente.  
  resources:
    requests:
      storage: 256Mi #La cantidad de almacenamiento solicitada para el volumen.